"""add_itinerary_columns

Revision ID: f300b3835b30
Revises: 1719ae1e8a7b
Create Date: 2026-07-17 00:45:53.910486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f300b3835b30'
down_revision: Union[str, Sequence[str], None] = '1719ae1e8a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('itinerary', sa.JSON(), nullable=True))
    op.add_column('trips', sa.Column('budget_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'budget_breakdown')
    op.drop_column('trips', 'itinerary')
    op.drop_column('trips', 'longitude')
    op.drop_column('trips', 'latitude')
    # ### end Alembic commands ###
